version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/dashboard"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/collector"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
